package com.a3008project.test.a3008_haptic;

public enum DataEnum {
    USER_ID, ENVIRONMENT, SCHEME, MODE, EVENT, RESULT, COOKIE, SEQUENCE,
    ATTEMPTS, USERTAPS, GENTAPS, GENSEQUENCE, CATEGORY, SOUND
}
